### ISSUE TITLE
The spacers were not included in Re40.

### ISSUE THREAD

**Issue by corelax-dev** [kushima8/Re#1]
I bought it at Yushu-kobo last week.But I couldn't find out the parts of the all spacers.

Please send me that.

**Comment by kushima8** [comment]
Sorry for the delay in realizing this.
First of all, I want to apologize for the missing items.
I'd like to send you the missing spacers.
I want to keep in touch with Twitter DirectMessage, is that okay?
https://twitter.com/kushima8

**Comment by corelax-dev** [comment]
Thank you for your support. I got spacers from you today.
