### ISSUE TITLE
スペーサーのフットプリントが、現実に流通しているものよりも小さいケースがある(かもしれない)

### ISSUE THREAD

**Issue by koron** [kushima8/Re#2]
### 経緯

1. re64l_bottom.dxf を本レポジトリよりダウンロードした
2. Jw_cad (8.22d) を用いて DXF に以下の修正を加えた
    * 全体を25.4倍に拡大し、単位をmmに変換した
    * 寸法線とその表記数値を削除した
    以上2点。加工会社の [ガイドライン](https://www.laserboost.com/design-guidelines) に従った修正
3. ステップ2で作成したDXFで業者に発注した
4. できてきたトッププレートを付けたところスタビライザー部分が装着できなかった
5. 0.1~0.2mmほど外側に向け、両端を削り広げることで装着した

### 計測など調査した情報

計測対象は左のトッププレートです。
DXF内のサイズはJw_cadを用いて `線長` および `測定` を用いて計測しました。

計測・調査対象 | `a` | `b` | `w` | `h` | 備考
---|---|---|---|---|--
オリジナルDXF | 0.265746in (6.75mm) | 1.20205in (30.53mm) | 0.5511in (14.0mm) | 0.5511in (14.0mm) | カッコ内は25.4倍してmm換算した値
加工後のDXF | 6.7499mm | 30.50mm | 13.999mm | 13.999mm | オリジナルのサイズを正確に表している
今回作成したアルミ | 6.7mm | 30.6mm | 14.0mm | 14.1mm | 若干怪しいところもあるがほぼ提出したDXF通りと言ってよい
アクリル(使用済) | 7.0mm | 30.8mm | 14.2mm | 14.2mm | 使用済みのため変形の可能性は否めない
[仕様書](https://github.com/kushima8/Re/files/5781624/MX.Series.pdf) からの抜粋 | 0.262±0.004in (6.65±0.10mm) | 0.94in+0.166in*2=1.272in (32.31mm) | 0.551in (14.0mm) | 0.551in (14.0mm) | `b` が実際よりもかなり広いのが謎。図面を読み間違えている可能性あり
使用しているスタビライザー | 6.8mm | 30.8mm | N/A | N/A | `b` は取り付けた状態での計測なのであまり意味はないが、今回作成したアルミがそのままでは入らないことがわかる。キースイッチは問題なく取り付けられている。

記号の意味:

* `a` - スタビライザーに2個付いたケーシングの幅
* `b` - スタビライザー穴の主幅(突出部分を含まない)
* `w` - キースイッチの穴の幅
* `h` - キースイッチの穴の高さ

以下は上記の計測場所を表す模式図

![image](https://user-images.githubusercontent.com/468368/103892407-dfcc8480-512e-11eb-9b2c-8702eb26ae8e.png)

### 考察

* オリジナルDXFと加工済みDXF、および実際にできたアルミトッププレートは誤差の範囲内
    * 上記を3点を仕様と照らし合わせても、謎な `b` を除いて不審な点はない
* [仕様書](https://github.com/kushima8/Re/files/5781624/MX.Series.pdf) と比較すると実際に利用したスタビライザーの片足の幅が広すぎる
* 実物のアクリルトッププレートは `a`, `b`, `w`, `h` すべてがオリジナルDXFと(大きい方向で)異なる
    * ゆえに同じスタビライザーを用いても装着できる
    * これが何に由来しているかは不明: キットのモノと本レポジトリにあるデータは別物?

### 各種情報

* アルミ加工会社: [LASER BOOST](https://www.laserboost.com/)
    * 1.5mm のアルミ(A5754使用)
    * SandBlasting仕上げ
    下記 re64l_top_x25_4.dxf の注文時情報
    ```
    Material: Aluminium 5754 SandBlasted
    Thickness: 1.5 mm
    Size: 138.16 x 103.81 mm
    Path Length: 2270.87 mm
    ```

    アクリルの実測値が  137.9mm x 103.5mm であったため問題なしと判断

* 使ったスタビライザー: [遊舎工房 MXスイッチスタビライザー 2u](https://yushakobo.jp/shop/a0500st/)
* スタビライザーの位置: 左側のシフトキー相当部分(R4 最左)
* DXFファイル: [re64l_top.zip](https://github.com/kushima8/Re/files/5781459/re64l_top.zip)
    ZIP内は以下の2ファイルが入ってます。
    * re64l_top.dxf オリジナルファイル。 [Re64/Plate/re64l_bottom.dxf](https://github.com/kushima8/Re/blob/0bae5dc5c3ff40ee3f0fa1444f8c82efd387edbd/Re64/Plate/re64l_bottom.dxf) より 2020-12-28 に取得
    * re64l_top_x25_4.dxf Jw_catを使って加工済み。加工内容は以下の通り
        * mm単位にするために全体を25.4倍にした
        * 長さ指示の表示を消した
* [MX Series.pdf](https://github.com/kushima8/Re/files/5781624/MX.Series.pdf) - どこかで見つけてきた Cherry MX の仕様書(?)。 Metal Frame Cutout Dimensions がある

**Comment by koron** [comment]
仕様書の `b` の一部である 0.166in は 0.131in の typo だったりしないだろうか?
だとすれば 1.202in (30.53mm) となりDXFと合致する。

**Comment by koron** [comment]
おっとスペーサーじゃないです。スタビライザーです…直しておきます。

**Comment by kushima8** [comment]
まずは、Gitに置いてあるdxfファイルがインチ出力していたものであり、
こちらの意図したファイルと異なっておりました。
業者に依頼する際も同じファイルを使用していたのですが、
問題なく納品されておりましたので今まで気づきませんでした。
お手数おかけしました。
現在はすべてmm出力のものと差し替えております。

トッププレートのスタビライザー穴の形状ですが、
こちらのものを参考に作成しております。
https://www.mouser.com/datasheet/2/71/mx_cat-1159901.pdf

こちらのデータシートですとbに該当する長さが14mm+6.65mm=30.45mmです。
2Uサイズのスタビライザーの大きさが30mmと聞いていましたので、
こちらの寸法から少しだけ大きくし、30.55mm前後になるように設計いたしました。

現在アルミトッププレートを装着し、同じスタビライザーを使用しているものがあるのですが、
問題なく装着でき可動しております。
しかし、設計がギリギリであるためプレートとスタビライザーの隙間がほぼない状態であります。

今回装着するにあたって、0.1～0.2mmほど削り広げたとのことですが、
穴の設計に余裕がなく、スタビライザーの個体差を許容できず装着できなかったものではないかと思われます。

**Comment by koron** [comment]
ありがとうございます。
ほんの少し削れば済む程度でしたので影響としては軽微というか
無いも同然です。

ただ1点だけキットに付属のアクリルトッププレートで
スタビライザーおよびキースイッチ用の穴寸法がDXFにくらべ約0.2mm大きい
ことだけが気にかかっています。
これはアクリルの加工方法に由来する誤差なのか
それとも何かしらの修正データによるものなのか
そこだけ心当たりがありましたら教えていただけると幸いです。

**Comment by koron** [comment]
更新後のDXFは後程チェックさせていただきます。

**Comment by kushima8** [comment]
加工を依頼した業者が使用しているレーザー幅が約0.2mmであり、
加工上線の両端約0.1mmが余分に削られている為、
DXFで指定した数値と実寸に誤差が発生しております。

**Comment by koron** [comment]
あーなるほど!完璧にスッキリしました。ありがとうございます。

**Comment by koron** [comment]
最後に判明した事実をまとめて本issueは閉じます。

* 游舎工房で販売しているスタビライザー足の幅 `a` はCherry MXの出している寸法と公差を超えて大きかった
    参考: 6.8mm > 0.262±0.004in (6.65±0.10mm)
* Re64のトッププレートは設計上 6.75mm なので公式に想定されたスタビライザーを挿入するのに十分な `a` である
* Re64のキットに含まれるアクリル製トッププレートは加工業者のレーザー幅のため 0.1mm ずつ多く削られる  
    `a` は理論値で 6.95mm 実測値 7.0mm となり「件のスタビライザー」を挿入できている
