### ISSUE TITLE
Re40:ファームウエアの書き込みで上手くできません

### ISSUE THREAD

**Issue by corelax-dev** [kushima8/Re#3]
以下サイトの手順で、「Auto-flash enabled」と出てこないです。キーボードのリセットボタンを押下してもメッセージが出ないのですが何が原因かご教示いただけますでしょうか。

https://salicylic-acid3.hatenablog.com/entry/qmk-toolbox 
-QMK Toolboxを使用する場合（旧説明内容）
 -Auto-Flashをオンにする
  -下図赤◯のチェックボックスをオンにし、下の黒い画面に「Auto-flash enabled」と出てくるのを確認する。

**Comment by kushima8** [comment]
申し訳ありませんがその情報だけですと原因が特定出来ません。
ProMicroのみの状態で書き込みが出来るかなど問題の切り分けを行ってから相談してください。
